openapi: 3.0.1
info:
  title: TIXY Public Organizer API
  version: 1.0.0
  description: >
    The TIXY Public Organizer API allows public users to access event and tour data. 
    It includes endpoints to fetch event and tour details based on status or specific identifiers.
servers:
  - url: https://public-api.tixyapp.com

paths:
  /events/{status}:
    get:
      summary: Retrieve public events by status
      description: >
        Fetches a list of public events filtered by the specified status. 
        Allows users to view events that are currently published, past due, or all available events.
      parameters:
        - name: status
          in: path
          required: true
          schema:
            type: string
            enum:
              - all
              - published
              - pastdue
          description: >
            The status of the events to retrieve. Valid values are:
            - `all`: Retrieve all events.
            - `published`: Retrieve currently published events.
            - `pastdue`: Retrieve past due events.
      security:
        - organizerApiAuthFunction: []
      responses:
        '200':
          description: >
            Successful response containing a list of events filtered by the specified status.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-integration:
        uri: 
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${organizerApiPublicEndpointsFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy
  /event/{id}:
    get:
      summary: Retrieve details for a specific public event
      description: >
        Fetches the details for a specific public event identified by its unique identifier or slug.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: >
            The unique identifier or slug of the event to retrieve.
      security:
        - organizerApiAuthFunction: []
      responses:
        '200':
          description: >
            Successful response containing the details of the specified event.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Event'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-integration:
        uri: 
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${organizerApiPublicEndpointsFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

  /tours/{status}:
    get:
      summary: Retrieve public tours by status
      description: >
        Fetches a list of public tours filtered by the specified status. 
        Allows users to view tours that are currently published, past due, or all available tours.
      parameters:
        - name: status
          in: path
          required: true
          schema:
            type: string
            enum:
              - all
              - published
              - pastdue
          description: >
            The status of the tours to retrieve. Valid values are:
            - `all`: Retrieve all tours.
            - `published`: Retrieve currently published tours.
            - `pastdue`: Retrieve past due tours.
      security:
        - organizerApiAuthFunction: []
      responses:
        '200':
          description: >
            Successful response containing a list of tours filtered by the specified status.
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/PublicTour'
        '400':
          $ref: '#/components/responses/BadRequest'
        '500':
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-integration:
        uri: 
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${organizerApiPublicEndpointsFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

  /tour/{id}:
    get:
      summary: Retrieve details for a specific public tour
      description: >
        Fetches the details for a specific public tour identified by its unique identifier or slug.
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
          description: >
            The unique identifier or slug of the tour to retrieve.
      security:
        - organizerApiAuthFunction: []
      responses:
        '200':
          description: >
            Successful response containing the details of the specified tour.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PublicTour'
        '400':
          $ref: '#/components/responses/BadRequest'
        '404':
          $ref: '#/components/responses/NotFound'
        '500':
          $ref: '#/components/responses/InternalServerError'
      x-amazon-apigateway-integration:
        uri: 
          Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${organizerApiPublicEndpointsFunction.Arn}/invocations
        httpMethod: POST
        type: aws_proxy

components:
  schemas:
    Event:
      type: object
      properties:
        social:
          type: object
          properties:
            links:
              type: array
              items:
                type: string
          description: "Social media links for the event."
        tickets:
          type: object
          properties:
            isTicketResselingEnabled:
              type: boolean
              example: false
              description: "Indicates if ticket reselling is enabled."
            tickets:
              type: array
              items:
                $ref: '#/components/schemas/Ticket'
          description: "Details of tickets associated with the event."
        dates:
          type: object
          properties:
            scanning:
              type: object
              properties:
                start:
                  type: string
                  format: date-time
                end:
                  type: string
                  format: date-time
              description: "Dates for ticket scanning."
            end:
              type: string
              format: date-time
            openings:
              type: array
              items:
                type: object
                properties:
                  date:
                    type: string
                    format: date-time
                  id:
                    type: string
                    format: uuid
          description: "Event date details."
        status:
          type: string
          description: "Status of the event."
        types:
          type: array
          items:
            type: string
          description: "Event types or categories."
        visibility:
          type: string
          description: "Visibility of the event."
        allowResale:
          type: boolean
          description: "Indicates if ticket resale is allowed."
        name:
          type: string
          description: "Name of the event."
        artistsDetails:
          type: string
          nullable: true
          description: "Details of artists performing at the event."
        publishTime:
          type: string
          format: date-time
        id:
          type: string
          format: uuid
        slug:
          type: string
          description: "URL-friendly identifier for the event."
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        category:
          type: string
          description: "Category of the event."
        restrictions:
          type: object
          properties:
            ageLimit:
              type: string
              example: "0"
        description:
          type: string
          description: "Detailed information about an event."
    Ticket:
      type: object
      properties:
        name:
          type: string
          example: "Bilet 1"
        description:
          type: string
          example: "bilet 1"
        id:
          type: string
          format: uuid
          example: "0b090e56-5895-499d-a3ee-ebc79c385112"
        ticketPools:
          type: array
          items:
            $ref: '#/components/schemas/TicketPool'
        isSinglePoolTicket:
          type: boolean
          example: true
        shouldDisplayTicketName:
          type: boolean
          example: true
    TicketPool:
      type: object
      properties:
        salesDates:
          type: object
          properties:
            start:
              type: string
              example: ""
            hasEndDate:
              type: boolean
              example: false
            end:
              type: string
              example: ""
            hasStartDate:
              type: boolean
              example: false
        id:
          type: string
          format: uuid
          example: "9e2dc72f-f284-4e9b-acc8-76cd71993628"
        salesActive:
          type: boolean
          example: true
        price:
          type: string
          example: "1"
    PublicTour:
      type: object
      properties:
        id:
          type: string
          description: Unique identifier for the tour.
        name:
          type: string
          description: Name of the tour.
        events:
          type: array
          description: List of events included in the tour.
          items:
            $ref: '#/components/schemas/Event'
        description:
          type: string
          description: A short description of the tour.
        status:
          type: string
          description: Current status of the tour (e.g., published, pastdue).
  securitySchemes:
    organizerApiAuthFunction:
      type: http
      scheme: bearer
      description: >
        Custom Bearer token authentication for accessing public organizer endpoints.
      x-amazon-apigateway-authtype: custom
      x-amazon-apigateway-authorizer:
        authorizerUri: 
          uri: 
            Fn::Sub: arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${organizerApiAuthFunction.Arn}/invocations
        authorizerResultTtlInSeconds: 300
        identitySource: method.request.header.Authorization
  responses:
    BadRequest:
      description: >
        Bad Request. The provided parameters are invalid or malformed.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: Explanation of the error.
              code:
                type: string
                description: Error code.
    NotFound:
      description: >
        Not Found. The requested resource was not found.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: Explanation of the error.
              code:
                type: string
                description: Error code.
    InternalServerError:
      description: >
        Internal Server Error. An unexpected error occurred.
      content:
        application/json:
          schema:
            type: object
            properties:
              message:
                type: string
                description: Explanation of the server error.
              code:
                type: string
                description: Error code.